services:
  - type: web
    name: agems-track-land
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 --threads 4 --timeout 180 app:app
    envVars:
      - key: AGEMS_SECRET_KEY
        sync: false
      - key: AGEMS_USERNAME
        sync: false
      - key: AGEMS_PASSWORD
        sync: false
      - key: SYSTEMSAT_HASH_AUTH
        sync: false
      - key: SYSTEMSAT_USERNAME
        sync: false
      - key: SYSTEMSAT_PASSWORD
        sync: false
      - key: MAPBOX_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: FLASK_DEBUG
        value: "0"
